#!/bin/bash
#====================================================
#	@vps10
#====================================================
# Definir colores y efectos
verde="\e[1;32m"  # Cian bold
azul="\e[1;34m"  # azul bold
cyan="\e[1;36m"  # cyan bold
rojo="\e[1;31m"  # Rojo bold
blanco="\e[1;37m"  # Blanco bold
amarillo="\e[1;33m"  # Amarillo bold
fin="\e[0m"   # fin del color
[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@KIRITO_SSH" ]] && {
	ram1=$(free -h | grep -i mem | awk {'print $2'})
	ram2=$(free -h | grep -i mem | awk {'print $4'})
	ram3=$(free -h | grep -i mem | awk {'print $3'})
	uso=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
	system=$(cat /etc/issue.net)
	fun_bar() {
		comando[0]="$1"
		comando[1]="$2"
		(
			[[ -e $HOME/fim ]] && rm $HOME/fim
			[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
			${comando[0]} >/dev/null 2>&1
			${comando[1]} >/dev/null 2>&1
			touch $HOME/fim
		) >/dev/null 2>&1 &
		tput civis
		echo -ne "${amarillo}AGUARDE ${blanco}- ${amarillo}["
		while true; do
			for ((i = 0; i < 18; i++)); do
				echo -ne "${rojo}#"
				sleep 0.1s
			done
			[[ -e $HOME/fim ]] && rm $HOME/fim && break
			echo -e "${amarillo}]"
			sleep 1s
			tput cuu1
			tput dl1
			echo -ne "${amarillo}AGUARDE ${blanco}- ${amarillo}["
		done
		echo -e "${amarillo}]${blanco} -${verde} OK !${blanco}"
		tput cnorm
	}

	verif_ptrs() {
		porta=$1
		PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
		for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
			svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
			[[ "$porta" = "$pton" ]] && {
				echo -e "\n${rojo}PORTA ${amarillo}$porta ${rojo}EM USO PELO ${blanco}$svcs${fin}"
				sleep 3
				fun_conexao
			}
		done
	}

	slow_setup() {
		[[ -e "/bin/slowdns" ]] && {
			slowdns
		} || {
			cd $HOME
			wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/main/Slowdns/install -o /dev/null
			chmod 777 install
			./install
		}

	}

	inst_sqd() {
		if netstat -nltp | grep 'squid' 1>/dev/null 2>/dev/null; then
			echo -e "\E[41;1;37m            REMOVER SQUID PROXY              ${fin}"
			echo ""
			echo -ne "${verde}REALMENTE DESEA REMOVER EL SQUID ${rojo}? ${amarillo}[s/n]:${blanco} "
			read resp
			[[ "$resp" = 's' ]] && {
				echo -e "\n${verde}REMOVENDO EL SQUID PROXY !${fin}"
				echo ""
				rem_sqd() {
					[[ -d "/etc/squid" ]] && {
						apt-get remove squid -y >/dev/null 2>&1
						apt-get purge squid -y >/dev/null 2>&1
						rm -rf /etc/squid >/dev/null 2>&1
					}
					[[ -d "/etc/squid3" ]] && {
						apt-get remove squid3 -y >/dev/null 2>&1
						apt-get purge squid3 -y >/dev/null 2>&1
						rm -rf /etc/squid3 >/dev/null 2>&1
						apt autoremove -y >/dev/null 2>&1
					}
				}
				fun_bar 'rem_sqd'
				echo -e "\n${verde}SQUID REMOVIDO CON SUCESSO !${fin}"
				sleep 2
				clear
				fun_conexao
			} || {
				echo -e "\n${rojo}Retornando...${fin}"
				sleep 2
				clear
				fun_conexao
			}
		else
			clear
			echo -e "\E[44;1;37m              INSTALADOR SQUID                ${fin}"
			echo ""
			IP=$(wget -qO- ipv4.icanhazip.com)
			echo -ne "${verde}PARA CONTINUAR CONFIRME SU IP: ${blanco}"
			read -e -i $IP ipdovps
			[[ -z "$ipdovps" ]] && {
				echo -e "\n${rojo}IP invalido${verde}"
				echo ""
				read -p "Digite seu IP: " IP
			}
			echo -e "\n${amarillo}CUAL PUERTO DESEA ULTILIZAR EN SQUID ${rojo}?"
			echo -e "\n${amarillo}[${rojo}!${amarillo}] ${verde}DEFINA LOS PORTOS EN SECUENCIA ${amarillo}EX: ${blanco}80 8080"
			echo ""
			echo -ne "${verde}INFORME LOS PORTOS${blanco}: "
			read portass
			[[ -z "$portass" ]] && {
				echo -e "\n${rojo}Porta invalida!"
				sleep 3
				fun_conexao
			}
			for porta in $(echo -e $portass); do
				verif_ptrs $porta
			done
			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
				echo -e "\n${verde}INSTALANDO SQUID PROXY${fin}\n"
				fun_bar 'apt update -y' "apt install squid3 -y"
			} || {
				echo -e "\n${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}SQUID VERSAO 3.3.X\n${rojo}[${cyan}2${rojo}] ${blanco}• ${amarillo}SQUID VERSAO 3.5.X${fin}\n"
				read -p "$(echo -e "${verde}INFORME UNA OPCION ${blanco}: ")" -e -i 1 opc
				[[ -z "$opc" ]] && {
					echo -e "\n${rojo}Opcao invalida!"
					sleep 2
					fun_conexao
				}
				[[ "$opc" != '1' ]] && {
					[[ "$opc" != '2' ]] && {
						echo -e "\n${rojo}Opcao invalida !"
						sleep 2
						fun_conexao
					}
				}
				echo -e "\n${verde}INSTALANDO SQUID PROXY${fin}\n"
				fun_bar 'apt update -y' "instsqd $opc"
			}
			if [[ -d "/etc/squid/" ]]; then
				var_sqd="/etc/squid/squid.conf"
				var_pay="/etc/squid/payload.txt"
			elif [[ -d "/etc/squid3/" ]]; then
				var_sqd="/etc/squid3/squid.conf"
				var_pay="/etc/squid3/payload.txt"
			else
				echo -e "\n${amarillo}[${rojo}ERRO${amarillo}]${blanco}: ${amarillo}O SQUID PROXY CORROMPIDO${fin}"
				sleep 2
				fun_conexao
			fi
			cat <<-EOF >$var_pay
				.whatsapp.net/
				.facebook.net/
				.twitter.com/
				.speedtest.net/
			EOF
			cat <<-EOF >$var_sqd
				acl url1 dstdomain -i 127.0.0.1
				acl url2 dstdomain -i localhost
				acl url3 dstdomain -i $ipdovps
				acl url4 dstdomain -i /SSHPLUS?
				acl payload url_regex -i "$var_pay"
				acl all src 0.0.0.0/0

				http_access allow url1
				http_access allow url2
				http_access allow url3
				http_access allow url4
				http_access allow payload
				http_access deny all
				 
				#Portas
			EOF
			for Pts in $(echo -e $portass); do
				echo -e "http_port $Pts" >>$var_sqd
				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
			done
			cat <<-EOF >>$var_sqd
				#Nome squid
				visible_hostname SSHPLUS 
				via off
				forwarded_for off
				pipeline_prefetch off
			EOF
			sqd_conf() {
				[[ -d "/etc/squid/" ]] && {
					service ssh restart
					/etc/init.d/squid restart
					service squid restart
				}
				[[ -d "/etc/squid3/" ]] && {
					service ssh restart
					/etc/init.d/squid3 restart
					service squid3 restart
				}
			}
			echo -e "\n${verde}CONFIGURANDO SQUID PROXY${fin}"
			echo ""
			fun_bar 'sqd_conf'
			echo -e "\n${verde}SQUID INSTALADO CON EXITO!${fin}"
			sleep 2.5s
			fun_conexao
		fi
	}

	addpt_sqd() {
		echo -e "\E[44;1;37m         ADICIONAR PUERTO A SQUID         ${fin}"
		echo -e "\n${amarillo}PUERTOS EN USO: ${verde}$sqdp\n"
		if [[ -f "/etc/squid/squid.conf" ]]; then
			var_sqd="/etc/squid/squid.conf"
		elif [[ -f "/etc/squid3/squid.conf" ]]; then
			var_sqd="/etc/squid3/squid.conf"
		else
			echo -e "\n${rojo}SQUID NO ESTA INSTALADO!${fin}"
			echo -e "\n${rojo}Retornando...${fin}"
			sleep 2
			clear
			fun_squid
		fi
		echo -ne "${verde}CUAL PUERTO DESEA ADICIONAR ${amarillo}?${blanco} "
		read pt
		[[ -z "$pt" ]] && {
			echo -e "\n${rojo}Porta invalida!"
			sleep 2
			clear
			fun_conexao
		}
		verif_ptrs $pt
		echo -e "\n${verde}ADICIONANDO PUERTO A SQUID!"
		echo ""
		sed -i "s/#Portas/#Portas\nhttp_port $pt/g" $var_sqd
		fun_bar 'sleep 2'
		echo -e "\n${verde}REINICIANDO O SQUID!"
		echo ""
		fun_bar 'service squid restart' 'service squid3 restart'
		echo -e "\n${verde}PORTA ADICIONADA COM SUCESSO!"
		sleep 3
		clear
		fun_squid
	}

	rempt_sqd() {
		echo -e "\E[41;1;37m        REMOVER PORTA DO SQUID        ${fin}"
		echo -e "\n${amarillo}PORTAS EM USO: ${verde}$sqdp\n"
		if [[ -f "/etc/squid/squid.conf" ]]; then
			var_sqd="/etc/squid/squid.conf"
		elif [[ -f "/etc/squid3/squid.conf" ]]; then
			var_sqd="/etc/squid3/squid.conf"
		else
			echo -e "\n${rojo}SQUID NAO ESTA INSTALADO!${fin}"
			echo -e "\n${rojo}Retornando...${fin}"
			sleep 2
			clear
			fun_squid
		fi
		echo -ne "${verde}QUAL PORTA DESEJA REMOVER ${amarillo}?${blanco} "
		read pt
		[[ -z "$pt" ]] && {
			echo -e "\n${rojo}Porta invalida!"
			sleep 2
			clear
			fun_conexao
		}
		if grep -E "$pt" $var_sqd >/dev/null 2>&1; then
			echo -e "\n${verde}REMOVENDO PORTA DO SQUID!"
			echo ""
			sed -i "/http_port $pt/d" $var_sqd
			fun_bar 'sleep 3'
			echo -e "\n${verde}REINICIANDO O SQUID!"
			echo ""
			fun_bar 'service squid restart' 'service squid3 restart'
			echo -e "\n${verde}PORTA REMOVIDA COM SUCESSO!"
			sleep 3.5s
			clear
			fun_squid
		else
			echo -e "\n${rojo}PORTA ${verde}$pt ${rojo}NAO ENCONTRADA!"
			sleep 3.5s
			clear
			fun_squid
		fi
	}

	fun_squid() {
		[[ "$(netstat -nplt | grep -c 'squid')" = "0" ]] && inst_sqd
		echo -e "\E[44;1;37m          GERENCIAR SQUID PROXY           ${fin}"
		[[ "$(netstat -nplt | grep -c 'squid')" != "0" ]] && {
			sqdp=$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)
			echo -e "\n${amarillo}PORTAS${blanco}: ${verde}$sqdp"
			VarSqdOn="REMOVER SQUID PROXY"
		} || {
			VarSqdOn="INSTALAR SQUID PROXY"
		}
		echo -e "\n${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}$VarSqdOn ${rojo}
[${cyan}2${rojo}] ${blanco}• ${amarillo}ADICIONAR PORTA ${rojo}
[${cyan}3${rojo}] ${blanco}• ${amarillo}REMOVER PORTA${rojo}
[${cyan}0${rojo}] ${blanco}• ${amarillo}VOLTAR${fin}"
		echo ""
		echo -ne "${verde}OQUE DESEJA FAZER ${amarillo}?${rojo}?${blanco} "
		read x
		clear
		case $x in
		1 | 01)
			inst_sqd
			;;
		2 | 02)
			addpt_sqd
			;;
		3 | 03)
			rempt_sqd
			;;
		0 | 00)
			echo -e "${rojo}Retornando...${fin}"
			sleep 1
			fun_conexao
			;;
		*)
			echo -e "${rojo}Opcao Invalida...${fin}"
			sleep 2
			fun_conexao
			;;
		esac
	}

	fun_drop() {
		if netstat -nltp | grep 'dropbear' 1>/dev/null 2>/dev/null; then
			clear
			[[ $(netstat -nltp | grep -c 'dropbear') != '0' ]] && dpbr=$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs) || sqdp="${rojo}INDISPONIVEL"
			if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
				stats='${verde}◉ '
			else
				stats='${rojo}○ '
			fi
			echo -e "\E[44;1;37m              MENU DROPBEAR               ${fin}"
			echo -e "\n${amarillo}PORTAS${blanco}: ${verde}$dpbr"
			echo ""
			echo -e "${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}LIMITER DROPBEAR $stats${fin}"
			echo -e "${rojo}[${cyan}2${rojo}] ${blanco}• ${amarillo}EDITAR PUERTO DROPBEAR${fin}"
			echo -e "${rojo}[${cyan}3${rojo}] ${blanco}• ${amarillo}REMOVER DROPBEAR${fin}"
			echo -e "${rojo}[${cyan}0${rojo}] ${blanco}• ${amarillo}VOLVER${fin}"
			echo ""
			echo -ne "${verde} QUE DESEA HACER ${amarillo}?${blanco} "
			read resposta
			if [[ "$resposta" = '1' ]]; then
				clear
				if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
					echo -e "${verde}Parando o limiter... ${fin}"
					echo ""
					fun_stplimiter() {
						pidlimiter=$(ps x | grep "limiter" | awk -F "pts" {'print $1'})
						kill -9 $pidlimiter
						screen -wipe
					}
					fun_bar 'fun_stplimiter' 'sleep 2'
					echo -e "\n${rojo} LIMITER DESACTIVADO ${fin}"
					sleep 3
					fun_drop
				else
					echo -e "\n${verde}Iniciando o limiter... ${fin}"
					echo ""
					fun_bar 'screen -d -m -t limiter droplimiter' 'sleep 3'
					echo -e "\n${verde}  LIMITER ACTIVADO ${fin}"
					sleep 3
					fun_drop
				fi
			elif [[ "$resposta" = '2' ]]; then
				echo ""
				echo -ne "${verde} CUAL PUERTO DESEA ULTILIZAR ${amarillo}?${blanco} "
				read pt
				echo ""
				verif_ptrs $pt
				var1=$(grep 'DROPBEAR_PORT=' /etc/default/dropbear | cut -d'=' -f2)
				echo -e "${verde}ALTERANDO PORTA DROPBEAR!"
				sed -i "s/\b$var1\b/$pt/g" /etc/default/dropbear >/dev/null 2>&1
				echo ""
				fun_bar 'sleep 2'
				echo -e "\n${verde}REINICIANDO DROPBEAR!"
				echo ""
				fun_bar 'service dropbear restart' '/etc/init.d/dropbear restart'
				echo -e "\n${verde}PUERTO ALTERADO OK!"
				sleep 3
				clear
				fun_conexao
			elif [[ "$resposta" = '3' ]]; then
				echo -e "\n${verde}REMOVENDO EL DROPBEAR !${fin}"
				echo ""
				fun_dropunistall() {
					service dropbear stop && /etc/init.d/dropbear stop
					apt-get autoremove dropbear -y
					apt-get remove dropbear-run -y
					apt-get remove dropbear -y
					apt-get purge dropbear -y
					rm -rf /etc/default/dropbear
				}
				fun_bar 'fun_dropunistall'
				echo -e "\n${verde}DROPBEAR REMOVIDO CON EXITO !${fin}"
				sleep 3
				clear
				fun_conexao
			elif [[ "$resposta" = '0' ]]; then
				echo -e "\n${rojo}Retornando...${fin}"
				sleep 2
				fun_conexao
			else
				echo -e "\n${rojo}Opcao invalida...${fin}"
				sleep 2
				fun_conexao
			fi
		else
			clear
			echo -e "\E[44;1;37m           INSTALADOR DROPBEAR              ${fin}"
			echo -e "\n${amarillo}WEP ESTAS POR  INSTALAR EL DROPBEAR !${fin}\n"
			echo -ne "${verde}DESEA CONTINUAR ${rojo}? ${amarillo}[s/n]:${blanco} "
			read resposta
			[[ "$resposta" = 's' ]] && {
				echo -e "\n${amarillo}DEFINA UN PORTO PARA  DROPBEAR !${fin}\n"
				echo -ne "${verde}CUAL  PUERTO ${amarillo}?${blanco} "
				read porta
				[[ -z "$porta" ]] && {
					echo -e "\n${rojo}Porta invalida!"
					sleep 3
					clear
					fun_conexao
				}
				verif_ptrs $porta
				echo -e "\n${verde}INSTALANDO EL DROPBEAR ! ${fin}"
				echo ""
				fun_instdrop() {
					apt-get update -y
					apt-get install dropbear -y
				}
				fun_bar 'fun_instdrop'
				fun_ports() {
					sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear >/dev/null 2>&1
					sed -i "s/DROPBEAR_PORT=22/DROPBEAR_PORT=$porta/g" /etc/default/dropbear >/dev/null 2>&1
					sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 110"/g' /etc/default/dropbear >/dev/null 2>&1
				}
				echo ""
				echo -e "${verde}CONFIGURANDO PUERTO DROPBEAR !${fin}"
				echo ""
				fun_bar 'fun_ports'
				grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config >/tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
				echo "PasswordAuthentication yes" >>/etc/ssh/sshd_config
				grep -v "^PermitTunnel yes" /etc/ssh/sshd_config >/tmp/ssh && mv /tmp/ssh /etc/ssh/sshd_config
				echo "PermitTunnel yes" >>/etc/ssh/sshd_config
				echo ""
				echo -e "${verde}FINALIZANDO INSTALACION !${fin}"
				echo ""
				fun_ondrop() {
					service dropbear start
					/etc/init.d/dropbear restart
				}
				fun_bar 'fun_ondrop' 'sleep 1'
				echo -e "\n${verde}INSTALACION CONCLUIDA ${amarillo}PORTA: ${blanco}$porta${fin}"
				[[ $(grep -c "/bin/false" /etc/shells) = '0' ]] && echo "/bin/false" >>/etc/shells
				sleep 2
				clear
				fun_conexao
			} || {
				echo""
				echo -e "${rojo}Retornando...${fin}"
				sleep 3
				clear
				fun_conexao
			}
		fi
	}
	fun_v2rayins() {
		clear
		v2rayinst() {
			source <(curl -sL https://raw.githubusercontent.com/vpsvip7/SSHPLUS/main/Modulos/v2ray)
			sleep 6
		}
		if netstat -tunlp | grep v2ray 1>/dev/null 2>/dev/null; then
			echo -e "\E[44;1;37m            INSTALADOR V2RAY             ${fin}"
			echo -e "\n${YELLOW}V2RAY JÁ ESTÁ INSTALADO\nDESEJA REINSTALAR? ${SCOLOR}\n"
			echo -ne "${GREEN}DESEJA CONTINUAR A REINSTALAÇÃO ? ${YELLOW}[s/n]:${SCOLOR} "
			read resp
			[[ "$resp" != @(s|sim|S|SIM) ]] && {
				echo -e "\n${RED}Retornando...${SCOLOR}"
				sleep 2
				conexao
			}
			v2rayinst
		else
			echo -e "\E[44;1;37m            INSTALADOR V2RAY             ${fin}"
			echo -e "\n${YELLOW}VAS A INSTALAR EL  METODO  V2RAY ! ${SCOLOR}\n"
			echo -ne "${GREEN}DESEA CONTINUAR LA INSTALACION ? ${YELLOW}[s/n]:${SCOLOR} "
			read resp
			[[ "$resp" != @(s|sim|S|SIM) ]] && {
				echo -e "\n${RED}Retornando...${SCOLOR}"
				sleep 2
				conexao
			}
			v2rayinst
		fi
	}
	fun_chisel() {
		clear
		echo -e "\E[44;1;37m            GERENCIAR CHISEL             ${fin}"
		echo ""

		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
			sks='${verde}ON'
			echo -e "${amarillo}PURTOS${blanco}: ${verde}$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
		} || {
			sks='${rojo}OFF'
		}
		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
			chiselsts="${verde}◉ "
		} || {
			chiselsts="${rojo}○ "
		}
		echo ""
		echo -e "${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}ACTIVAR CHISEL $chiselsts ${fin}"
		echo -e "${rojo}[${cyan}2${rojo}] ${blanco}• ${amarillo}REINICIAR CHISEL${fin}"
		echo -e "${rojo}[${cyan}0${rojo}] ${blanco}• ${amarillo}VOLTAR${fin}"
		echo ""
		echo -ne "${verde}OQUE DESEJA FAZER ${amarillo}?${blanco} "
		read resposta
		if [[ "$resposta" = '1' ]]; then
			if netstat -nltp | grep 'docker' 1>/dev/null 2>/dev/null; then
				clear
				echo -e "\E[41;1;37m             CHISEL              ${fin}"
				echo ""
				fun_chiseloff() {
					docker stop chisel
					docker rm chisel
					docker.io stop chisel
					docker.io rm chisel

				}
				echo -e "${verde}DESACTIVANDO CHISEL${amarillo}"
				echo ""
				fun_bar 'fun_chiseloff'
				echo ""
				echo -e "${verde}CHISEL DESACTIVADO CON SUCESSO!${amarillo}"
				sleep 3
				fun_chisel
			else
				clear
				fun_installdocker() {
					_pacotes=("docker" "docker.io")
					for _prog in ${_pacotes[@]}; do
						apt install $_prog -y
					done
				}
				echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESE METODO É INSTAVEL\nPODE OU NO FUNCIONAR NA SUA MAQUINA\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
				echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
				read resp
				[[ "$resp" != @(s|sim|S|SIM) ]] && {
					echo -e "\n${RED}Retornando...${SCOLOR}"
					sleep 2
					conexao
				}
				echo -e "\n${verde}Suportado Ubuntu 16+${amarillo}"
				echo -e "\n${verde}INSTALANDO O CHISEL !${amarillo}"
				echo ""
				fun_bar 'fun_installdocker'
				clear
				echo -e "\E[44;1;37m             CHISEL              ${fin}"
				echo ""
				echo -ne "${verde}QUAL PORTA DESEJ ULTILIZAR ${amarillo}?${blanco}: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 3
					clear
					fun_chisel
				}
				verif_ptrs $porta
				clear
				echo -ne "${verde}Nome do usuário:${blanco} "
				read username
				[[ -z $username ]] && {
					echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
					fun_chisel
				}
				[[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
					echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
					echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
					fun_chisel
				}
				sizemin=$(echo ${#username})
				[[ $sizemin -lt 2 ]] && {
					echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
					echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
					fun_chisel
				}
				sizemax=$(echo ${#username})
				[[ $sizemax -gt 10 ]] && {
					echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
					echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
					fun_chisel
				}
				echo -ne "${verde}Senha:${blanco} "
				read password
				[[ -z $password ]] && {
					echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
					fun_chisel
				}
				sizepass=$(echo ${#password})
				[[ $sizepass -lt 4 ]] && {
					echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
					fun_chisel
				}
				echo -e "\n${verde}CONFIGURANDO CHISEL !${fin}"
				echo ""
				fun_inichisel() {
					docker run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
					docker.io run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
				}
				fun_bar 'fun_inichisel'
				clear
				echo -e "\n${verde}CHISEL INSTALADO COM SUCESSO !${rojo} PORTA: ${amarillo}${porta}${fin}"
				sleep 3
				clear
				fun_chisel
			fi
		elif [[ "$resposta" = '2' ]]; then
			clear
			echo -e "\n${verde}REINICIANDO CHISEL !${amarillo}"
			echo ""
			fun_attchisel() {
				docker restart chisel
				docker.io restart chisel
			}
			fun_attchisel
			clear
			echo -e "\n${verde}CHISEL REINICIANDO COM SUCESSO !${amarillo}"
			sleep 1
			fun_chisel
		elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "${rojo}Retornando...${fin}"
			sleep 1
			fun_conexao
		else
			echo ""
			echo -e "${rojo}Opcao invalida !${fin}"
			sleep 1
			fun_socks
		fi
	}
	inst_ssl() {
		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="${rojo}INDISPONIVEL"
			echo -e "\E[44;1;37m              MENU SSL TUNNEL               ${fin}"
			echo -e "\n${amarillo}PORTAS${blanco}: ${verde}$sslt"
			echo ""
			echo -e "${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}ALTERAR PORTA SSL TUNNEL${fin}"
			echo -e "${rojo}[${cyan}2${rojo}] ${blanco}• ${amarillo}REMOVER SSL TUNNEL${fin}"
			echo -e "${rojo}[${cyan}0${rojo}] ${blanco}• ${amarillo}VOLTAR${fin}"
			echo ""
			echo -ne "${verde}OQUE DESEJA FAZER ${amarillo}?${blanco} "
			read resposta
			echo ""
			[[ "$resposta" = '1' ]] && {
				echo -ne "${verde}QUAL PORTA DESEA ULTILIZAR ${amarillo}?${blanco} "
				read porta
				echo ""
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 2
					clear
					fun_conexao
				}
				verif_ptrs $porta
				echo -e "${verde}ALTERANDO PORTA SSL TUNNEL!"
				var2=$(grep 'accept' /etc/stunnel/stunnel.conf | awk '{print $NF}')
				sed -i "s/\b$var2\b/$porta/g" /etc/stunnel/stunnel.conf >/dev/null 2>&1
				echo ""
				fun_bar 'sleep 2'
				echo ""
				echo -e "${verde}REINICIANDO SSL TUNNEL!\n"
				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
				echo ""
				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "${verde}PORTA ALTERADA COM SUCESSO !" || echo -e "${rojo}ERRO INESPERADO!"
				sleep 3.5s
				clear
				fun_conexao
			}
			[[ "$resposta" = '2' ]] && {
				echo -e "${verde}REMOVENDO O  SSL TUNNEL !${fin}"
				del_ssl() {
					service stunnel4 stop
					apt-get remove stunnel4 -y
					apt-get autoremove stunnel4 -y
					apt-get purge stunnel4 -y
					rm -rf /etc/stunnel/stunnel.conf
					rm -rf /etc/default/stunnel4
					rm -rf /etc/stunnel/cert.cert
					rm -rf /etc/stunnel/key.key
				}
				echo ""
				fun_bar 'del_ssl'
				echo ""
				echo -e "${verde}SSL TUNNEL REMOVIDO COM SUCESSO!${fin}"
				sleep 3
				fun_conexao
			}
		else
			clear
			echo -e "\E[44;1;37m              INSTALAR SSL TUNNEL               ${fin}"
			echo ""
			echo -e "${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}INSTALAR SSL TUNNEL PADRÃO${fin}"
			echo -e "${rojo}[${cyan}2${rojo}] ${blanco}• ${amarillo}INSTALAR SSL TUNNEL WEBSOCKET${fin}"
			echo -e "${rojo}[${cyan}0${rojo}] ${blanco}• ${amarillo}VOLTAR${fin}"
			echo ""
			echo -ne "${verde}OQUE DESEJA FAZER ${amarillo}?${blanco} "
			read resposta
			echo ""
			if [[ "$resposta" = '1' ]]; then
				portssl='22'
			elif [[ "$resposta" = '2' ]]; then
				portssl='80'
			elif [[ "$resposta" = '0' ]]; then
				echo -e "${rojo}Retornando...${fin}"
				sleep 3
				fun_conexao
			else
				echo ""
				echo -e "${rojo}Opcao invalida !${fin}"
				sleep 1
				inst_ssl
			fi
			clear
			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             ${fin}"
			echo -e "\n${amarillo}VC ESTA PRESTES A INSTALAR O SSL TUNNEL !${fin}"
			echo ""
			echo -ne "${verde}DESEJA CONTINUAR ${rojo}? ${amarillo}[s/n]:${blanco} "
			read resposta
			[[ "$resposta" = 's' ]] && {
				echo -e "\n${amarillo}DEFINA UMA PORTA PARA O SSL TUNNEL !${fin}"
				echo ""
				read -p "$(echo -e "${verde}QUAL PORTA DESEJA UTILIZAR? ${blanco}")" -e -i 443 porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 3
					clear
					fun_conexao
				}
				verif_ptrs $porta
				echo -e "\n${verde}INSTALANDO O SSL TUNNEL !${amarillo}"
				echo ""
				fun_bar 'apt-get update -y' 'apt-get install stunnel4 -y'
				echo -e "\n${verde}CONFIGURANDO O SSL TUNNEL !${fin}"
				echo ""
				ssl_conf() {
					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${portssl}\naccept = ${porta}" >/etc/stunnel/stunnel.conf
				}
				fun_bar 'ssl_conf'
				echo -e "\n${verde}CRIANDO CERTIFICADO !${fin}"
				echo ""
				ssl_certif() {
					crt='EC'
					openssl genrsa -out key.pem 2048 >/dev/null 2>&1
					(
						echo $crt
						echo $crt
						echo $crt
						echo $crt
						echo $crt
						echo $crt
						echo $crt
					) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
					cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
					rm key.pem cert.pem >/dev/null 2>&1
					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
				}
				fun_bar 'ssl_certif'
				echo -e "\n${verde}INICIANDO O SSL TUNNEL !${fin}"
				echo ""
				fun_finssl() {
					service stunnel4 restart
					service ssh restart
					/etc/init.d/stunnel4 restart
				}
				fun_bar 'fun_finssl' 'service stunnel4 restart'
				echo -e "\n${verde}SSL TUNNEL INSTALADO COM SUCESSO !${rojo} PORTA: ${amarillo}$porta${fin}"
				sleep 1
				clear
				echo -e "Corrigindo SSL CLARO"
				cd /etc/stunnel/
				rm -rf stunnel.conf
				rm -rf stunnel.pem
				wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/main/Install/cert
				wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/main/Install/key
				wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/main/Install/stunnel
				mv cert cert.pem
				mv key key.pem
				mv stunnel stunnel.conf
				chmod 777 cert.pem
				chmod 777 key.pem
				chmod 777 stunnel.conf
				service stunnel4 restart
				cd $HOME
				clear
				echo -e "Corrigido"
				sleep 2
				fun_conexao
			} || {
				echo -e "\n${rojo}Retornando...${fin}"
				sleep 2
				clear
				fun_conexao
			}
		fi
	}

	fun_openvpn() {
		rm -rf /root/*   && wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/refs/heads/main/Modulos/ubuntu22.sh && ./ubuntu22.sh
		sleep 3
		fun_conexao
	}
	fun_ddos() {
		sudo apt install dnsutils
		apt-get install net-tools
		apt-get install tcpdump
		apt-get install unzip
		sudo apt-get install dsniff -y
		sudo apt install grepcidr
		wget https://github.com/jgmdev/ddos-deflate/archive/master.zip -O ddos.zip
unzip ddos.zip
		cd ddos-deflate-master
		./install.sh
		sleep 9
		fun_conexao
	}

	fun_socks() {
		clear
		echo -e "\E[44;1;37m             PROXY WEBSOCKET             ${fin}"
		echo ""
		[[ $(netstat -nplt | grep -wc 'python3') != '0' ]] && {
			sks='${verde}ON'
			echo -e "${amarillo}PUERTOS${blanco}: ${verde}$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)"
		} || {
			sks='${rojo}OFF'
		}
		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="${verde}◉" || var_sks1="${rojo}○"
		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="${verde}◉" || var_sks2="${rojo}○"
		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="${verde}◉" || sksop="${rojo}○"
		echo ""
		echo -e "${cyan}-1-  ${amarillo}SOCKS SSH $var_sks1 ${fin}"
		echo -e "${cyan}-2- • ${amarillo}WEBSOCKET mod $var_sks2 ${fin}"
		echo -e "${cyan}-3- • ${amarillo}SOCKS OPENVPN $sksop ${fin}"
		echo -e "${cyan}-4- • ${amarillo}ABRIR PUERTO${fin}"
		echo -e "${cyan}-5- • ${amarillo}ALTERAR BANNER SOCKS SSH${fin}"
		echo -e "${cyan}-6- • ${amarillo}ALTERAR BANNER WEBSOCKET${fin}"
		echo -e "${cyan}-0- • ${amarillo}VOLVER ${fin}"
		echo ""
		echo -ne "${verde} QUE DESEA HAZER ${amarillo}?${blanco} "
		read resposta
		if [[ "$resposta" = '1' ]]; then
			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				echo -e "\E[41;1;37m             PROXY SOCKS              ${fin}"
				echo ""
				fun_socksoff() {
					for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
						screen -r -S "$pidproxy" -X quit
					done
					[[ $(grep -wc "proxy.py" /etc/autostart) != '0' ]] && {
						sed -i '/proxy.py/d' /etc/autostart
					}
					sleep 1
					screen -wipe >/dev/null
				}
				echo -e "${verde}DESACTIVANDO  PROXY SOCKS${amarillo}"
				echo ""
				fun_bar 'fun_socksoff'
				echo ""
				echo -e "${verde}PROXY SOCKS DESACTIVADO CON SUCESSO!${amarillo}"
				sleep 3
				fun_socks
			else
				clear
				echo -e "\E[44;1;37m             PROXY SOCKS              ${fin}"
				echo ""
				echo -ne "${verde}CUAL PUERTO DESEA ULTILIZAR ${amarillo}?${blanco}: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 3
					clear
					fun_conexao
				}
				verif_ptrs $porta
				fun_inisocks() {
					sleep 1
					screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta
					[[ $(grep -wc "proxy.py" /etc/autostart) = '0' ]] && {
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
					} || {
						sed -i '/proxy.py/d' /etc/autostart
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxy' -X quit;  screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta; }" >>/etc/autostart
					}
				}
				echo ""
				echo -e "${verde}INICIANDO  WEBSOCKET${amarillo}"
				echo ""
				fun_bar 'fun_inisocks'
				echo ""
				echo -e "${verde}SOCKS ATIVADO CON SUCESSO${amarillo}"
				sleep 3
				fun_socks
			fi
		elif [[ "$resposta" = '2' ]]; then
			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				echo -e "\E[41;1;37m             WEBSOCKET              ${fin}"
				echo ""
				fun_wssocksoff() {
					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
						screen -r -S "$pidproxy" -X quit
					done
					[[ $(grep -wc "wsproxy.py" /etc/autostart) != '0' ]] && {
						sed -i '/wsproxy.py/d' /etc/autostart
					}
					sleep 1
					screen -wipe >/dev/null
				}
				echo -e "${verde}DESACTIVANDO  WEBSOCKET${amarillo}"
				echo ""
				fun_bar 'fun_wssocksoff'
				echo ""
				echo -e "${verde}WEBSOCKET DESACTIVADO CON SUCESSO!${amarillo}"
				sleep 3
				fun_socks
			else
				clear
				echo -e "\E[44;1;37m             WEBSOCKET              ${fin}"
				echo ""
				echo -ne "${verde}CUAL PUERTO DESEA ULTILIZAR ${amarillo}?${blanco}: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 3
					clear
					fun_conexao
				}
				verif_ptrs $porta
				fun_iniwssocks() {
					sleep 1
					screen -dmS python3 /etc/SSHPlus/wsproxy.py $porta
					[[ $(grep -wc "wsproxy.py" /etc/autostart) = '0' ]] && {
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS  python3 /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
					} || {
						sed -i '/wsproxy.py/d' /etc/autostart
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS  python3 /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
					}
				}
				echo ""
				echo -e "${verde}INICIANDO  WEBSOCKET${amarillo}"
				echo ""
				fun_bar 'fun_iniwssocks'
				echo ""
				echo -e "\e[1;32WS SOCKS ATIVADO CON SUCESSO${amarillo}"
				sleep 3
				fun_socks
			fi
		elif [[ "$resposta" = '3' ]]; then
			if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				echo -e "\E[41;1;37m            SOCKS OPENVPN             ${fin}"
				echo ""
				fun_socksopenoff() {
					for pidproxy in $(screen -list | grep -w "openpy" | awk {'print $1'}); do
						screen -r -S "$pidproxy" -X quit
					done
					[[ $(grep -wc "open.py" /etc/autostart) != '0' ]] && {
						sed -i '/open.py/d' /etc/autostart
					}
					sleep 1
					screen -wipe >/dev/null
				}
				echo -e "${verde}DESATIVANDO  SOCKS OPEN${amarillo}"
				echo ""
				fun_bar 'fun_socksopenoff'
				echo ""
				echo -e "${verde}SOCKS DESATIVADO CON SUCESSO!${amarillo}"
				sleep 2
				fun_socks
			else
				clear
				echo -e "\E[41;1;37m            SOCKS OPENVPN             ${fin}"
				echo ""
				echo -ne "${verde}CUAL PORTA DESEA ULTILIZAR ${amarillo}?${blanco}: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 2
					clear
					fun_conexao
				}
				verif_ptrs $porta
				fun_inisocksop() {
					[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
						listoldop=$(grep -w 'DEFAULT_HOST =' /etc/SSHPlus/open.py | cut -d"'" -f2 | cut -d: -f2)
						listopen=$(netstat -tlpn | grep -w openvpn | grep -v 127.0.0.1 | awk {'print $4'} | cut -d: -f2)
						sed -i "s/$listoldop/$listopen/" /etc/SSHPlus/open.py
					}
					sleep 1
					screen -dmS openpy python3 /etc/SSHPlus/open.py $porta
					[[ $(grep -wc "open.py" /etc/autostart) = '0' ]] && {
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'openpy' -X quit;  screen -dmS openpy python3 /etc/SSHPlus/open.py $porta; }" >>/etc/autostart
					} || {
						sed -i '/open.py/d' /etc/autostart
						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'openpy' -X quit;  screen -dmS openpy python3 /etc/SSHPlus/open.py $porta; }" >>/etc/autostart
					}
				}
				echo ""
				echo -e "${verde}INICIANDO O SOCKS OPENVPN${amarillo}"
				echo ""
				fun_bar 'fun_inisocksop'
				echo ""
				echo -e "${verde}SOCKS OPENVPN ATIVADO COM SUCESSO${amarillo}"
				sleep 3
				fun_socks
			fi
		elif [[ "$resposta" = '4' ]]; then
			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				sockspt=$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)
				clear
				echo -e "\E[44;1;37m            PROXY SOCKS             ${fin}"
				echo ""
				echo -e "${amarillo}PUERTOS EN USO: ${verde}$sockspt"
				echo ""
				echo -ne "${verde} CUAL PUERTO DESEA ULTILIZAR ${amarillo}?${blanco}: "
				read porta
				[[ -z "$porta" ]] && {
					echo ""
					echo -e "${rojo}Porta invalida!"
					sleep 2
					clear
					fun_conexao
				}
				verif_ptrs $porta
				echo ""
				echo -e "${verde}INICIANDO O PROXY SOCKS EN PUERTO ${rojo}$porta${amarillo}"
				echo ""
				abrirptsks() {
					sleep 1
					screen -dmS proxy python3 /etc/SSHPlus/proxy.py $porta
					sleep 1
				}
				fun_bar 'abrirptsks'
				echo ""
				echo -e "${verde}PROXY SOCKS ATIVADO CON SUCESSO${amarillo}"
				sleep 2
				fun_socks
			else
				clear
				echo -e "${rojo}FUNCION NO DISPONIBLE\n\n${amarillo}ACTIVE  SOCKS PRIMERO !${amarillo}"
				sleep 2
				fun_socks
			fi
		elif [[ "$resposta" = '5' ]]; then
			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				msgsocks=$(cat /etc/SSHPlus/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
				echo -e "\E[44;1;37m             PROXY SOCKS              ${fin}"
				echo ""
				echo -e "${amarillo}STATUS: ${verde}$msgsocks"
				echo""
				echo -ne "${verde}INFORME SU STATUS${rojo}:${blanco} "
				read msgg
				[[ -z "$msgg" ]] && {
					echo -e "\n${rojo}Status invalido!"
					sleep 2
					fun_conexao
				}
				[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
					echo -e "\n${rojo}[${amarillo}!${rojo}]${amarillo} EVITE CARACTERES ESPECIAIS${fin}"
					sleep 2
					fun_socks
				}
				echo -e "\n${rojo}[${cyan}01${rojo}]${amarillo} AZUL"
				echo -e "${rojo}[${cyan}02${rojo}]${amarillo} VERDE"
				echo -e "${rojo}[${cyan}03${rojo}]${amarillo} VERMELHO"
				echo -e "${rojo}[${cyan}04${rojo}]${amarillo} AMARILLO"
				echo -e "${rojo}[${cyan}05${rojo}]${amarillo} ROSA"
				echo -e "${rojo}[${cyan}06${rojo}]${amarillo} CYANO"
				echo -e "${rojo}[${cyan}07${rojo}]${amarillo} LARANJA"
				echo -e "${rojo}[${cyan}08${rojo}]${amarillo} ROJO"
				echo -e "${rojo}[${cyan}09${rojo}]${amarillo} PRETO"
				echo -e "${rojo}[${cyan}10${rojo}]${amarillo} SIN COLOR"
				echo ""
				echo -ne "${verde}QUAL A COR${rojo} ?${blanco} : "
				read sts_cor
				if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
					cor_sts='blue'
				elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
					cor_sts='green'
				elif [[ "$sts_cor" = "3" ]] || [[ "$sts_cor" = "03" ]]; then
					cor_sts='red'
				elif [[ "$sts_cor" = "4" ]] || [[ "$sts_cor" = "04" ]]; then
					cor_sts='yellow'
				elif [[ "$sts_cor" = "5" ]] || [[ "$sts_cor" = "05" ]]; then
					cor_sts='#F535AA'
				elif [[ "$sts_cor" = "6" ]] || [[ "$sts_cor" = "06" ]]; then
					cor_sts='cyan'
				elif [[ "$sts_cor" = "7" ]] || [[ "$sts_cor" = "07" ]]; then
					cor_sts='#FF7F00'
				elif [[ "$sts_cor" = "8" ]] || [[ "$sts_cor" = "08" ]]; then
					cor_sts='#9932CD'
				elif [[ "$sts_cor" = "9" ]] || [[ "$sts_cor" = "09" ]]; then
					cor_sts='black'
				elif [[ "$sts_cor" = "10" ]]; then
					cor_sts='null'
				else
					echo -e "\n${amarillo}OPCION INVALIDA !"
					cor_sts='null'
				fi
				fun_msgsocks() {
					msgsocks2=$(cat /etc/SSHPlus/proxy.py | grep "MSG =" | awk -F = '{print $2}')
					sed -i "s/$msgsocks2/ '$msgg'/g" /etc/SSHPlus/proxy.py
					sleep 1
					cor_old=$(grep 'color=' /etc/SSHPlus/proxy.py | cut -d '"' -f2)
					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/SSHPlus/proxy.py
				}
				echo ""
				echo -e "${verde}ALTERANDO STATUS!"
				echo ""
				fun_bar 'fun_msgsocks'
				restartsocks() {
					if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
						echo -e "$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_sks
						for pidproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
							screen -r -S "$pidproxy" -X quit
						done
						screen -wipe >/dev/null
						_Ptsks="$(cat /tmp/Pt_sks)"
						sleep 1
						screen -dmS proxy python3 /etc/SSHPlus/proxy.py $_Ptsks
						rm /tmp/Pt_sks
					fi
				}
				echo ""
				echo -e "${verde}REINICIANDO PROXY SOCKS!"
				echo ""
				fun_bar 'restartsocks'
				echo ""
				echo -e "${verde}STATUS ALTERADO CON SUCESSO!"
				sleep 2
				fun_socks
			else
				clear
				echo -e "${rojo}FUNCION NO  DISPONIBLE\n\n${amarillo}ACTIVE  SOCKS SSH PRIMERO !${amarillo}"
				sleep 2
				fun_socks
			fi
		elif [[ "$resposta" = '6' ]]; then
			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
				clear
				msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
				echo -e "\E[44;1;37m             WEBSOCKET              ${fin}"
				echo ""
				echo -e "${amarillo}STATUS: ${verde}$msgsocks"
				echo""
				echo -ne "${verde}INFORME SU STATUS${rojo}:${blanco} "
				read msgg
				[[ -z "$msgg" ]] && {
					echo -e "\n${rojo}Status invalido!"
					sleep 2
					fun_conexao
				}
				[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
					echo -e "\n${rojo}[${amarillo}!${rojo}]${amarillo} EVITE CARACTERES ESPECIAIS${fin}"
					sleep 2
					fun_socks
				}
				echo -e "\n${rojo}[${cyan}01${rojo}]${amarillo} AZUL"
				echo -e "${rojo}[${cyan}02${rojo}]${amarillo} VERDE"
				echo -e "${rojo}[${cyan}03${rojo}]${amarillo} VERMELHO"
				echo -e "${rojo}[${cyan}04${rojo}]${amarillo} AMARILLO"
				echo -e "${rojo}[${cyan}05${rojo}]${amarillo} ROSA"
				echo -e "${rojo}[${cyan}06${rojo}]${amarillo} CYANO"
				echo -e "${rojo}[${cyan}07${rojo}]${amarillo} LARANJA"
				echo -e "${rojo}[${cyan}08${rojo}]${amarillo} ROJO"
				echo -e "${rojo}[${cyan}09${rojo}]${amarillo} PRETO"
				echo -e "${rojo}[${cyan}10${rojo}]${amarillo} SEM COR"
				echo ""
				echo -ne "${verde}CUAL  COLOR${rojo} ?${blanco} : "
				read sts_cor
				if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
					cor_sts='blue'
				elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
					cor_sts='green'
				elif [[ "$sts_cor" = "3" ]] || [[ "$sts_cor" = "03" ]]; then
					cor_sts='red'
				elif [[ "$sts_cor" = "4" ]] || [[ "$sts_cor" = "04" ]]; then
					cor_sts='yellow'
				elif [[ "$sts_cor" = "5" ]] || [[ "$sts_cor" = "05" ]]; then
					cor_sts='#F535AA'
				elif [[ "$sts_cor" = "6" ]] || [[ "$sts_cor" = "06" ]]; then
					cor_sts='cyan'
				elif [[ "$sts_cor" = "7" ]] || [[ "$sts_cor" = "07" ]]; then
					cor_sts='#FF7F00'
				elif [[ "$sts_cor" = "8" ]] || [[ "$sts_cor" = "08" ]]; then
					cor_sts='#9932CD'
				elif [[ "$sts_cor" = "9" ]] || [[ "$sts_cor" = "09" ]]; then
					cor_sts='black'
				elif [[ "$sts_cor" = "10" ]]; then
					cor_sts='null'
				else
					echo -e "\n${amarillo}OPCAO INVALIDA !"
					cor_sts='null'
				fi
				fun_msgsocks() {
					msgsocks2=$(cat /etc/SSHPlus/wsproxy.py | grep "MSG =" | awk -F = '{print $2}')
					sed -i "s/$msgsocks2/ '$msgg'/g" /etc/SSHPlus/wsproxy.py
					sleep 1
					cor_old=$(grep 'color=' /etc/SSHPlus/wsproxy.py | cut -d '"' -f2)
					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/SSHPlus/wsproxy.py
				}
				echo ""
				echo -e "${verde}ALTERANDO STATUS!"
				echo ""
				fun_bar 'fun_msgsocks'
				restartwssocks() {
					if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
						echo -e "$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_wssks
						for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
							screen -r -S "$pidproxy" -X quit
						done
						screen -wipe >/dev/null
						_Ptwssks="$(cat /tmp/Pt_wssks)"
						sleep 1
						screen -dmS  python3 /etc/SSHPlus/wsproxy.py $_Ptwssks
						rm /tmp/Pt_wssks
					fi
				}
				echo ""
				echo -e "${verde}REINICIANDO WEBSOCKET!"
				echo ""
				fun_bar 'restartwssocks'
				echo ""
				echo -e "${verde}STATUS ALTERADO COM SUCESSO!"
				sleep 2
				fun_socks
			else
				clear
				echo -e "${rojo}FUNCION NO DISPONIBLE\n\n${amarillo}ACTIVE  WEBSOCKET PRIMERO !${amarillo}"
				sleep 2
				fun_socks
			fi
		elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "${rojo}Retornando...${fin}"
			sleep 1
			fun_conexao
		else
			echo ""
			echo -e "${rojo}Opcao invalida !${fin}"
			sleep 1
			fun_socks
		fi

	}

	fun_openssh() {
		clear
		echo -e "\E[44;1;37m            OPENSSH             ${fin}\n"
		echo -e "${rojo}[${cyan}1${rojo}] ${blanco}• ${amarillo}ADICIONAR PORTA${rojo}
[${cyan}2${rojo}] ${blanco}• ${amarillo}REMOVER PORTA${rojo}
[${cyan}3${rojo}] ${blanco}• ${amarillo}VOLTAR${fin}"
		echo ""
		echo -ne "${verde}OQUE DESEJA FAZER ${amarillo}?${blanco} "
		read resp
		if [[ "$resp" = '1' ]]; then
			clear
			echo -e "\E[44;1;37m         ADICIONAR PORTA AO SSH         ${fin}\n"
			echo -ne "${verde}QUAL PORTA DESEJA ADICIONAR ${amarillo}?${blanco} "
			read pt
			[[ -z "$pt" ]] && {
				echo -e "\n${rojo}Porta invalida!"
				sleep 3
				fun_conexao
			}
			verif_ptrs $pt
			echo -e "\n${verde}ADICIONANDO PORTA AO SSH${fin}"
			echo ""
			fun_addpssh() {
				echo "Port $pt" >>/etc/ssh/sshd_config
				service ssh restart
			}
			fun_bar 'fun_addpssh'
			echo -e "\n${verde}PORTA ADICIONADA COM SUCESSO${fin}"
			sleep 3
			fun_conexao
		elif [[ "$resp" = '2' ]]; then
			clear
			echo -e "\E[41;1;37m         REMOVER PORTA DO SSH         ${fin}"
			echo -e "\n${amarillo}[${rojo}!${amarillo}] ${verde}PORTA PADRAO ${blanco}22 ${amarillo}CUIDADO !${fin}"
			echo -e "\n${amarillo}PORTAS EM USO: ${blanco}$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
			echo -ne "${verde}QUAL PORTA DESEJA REMOVER ${amarillo}?${blanco} "
			read pt
			[[ -z "$pt" ]] && {
				echo -e "\n${rojo}Porta invalida!"
				sleep 2
				fun_conexao
			}
			[[ $(grep -wc "$pt" '/etc/ssh/sshd_config') != '0' ]] && {
				echo -e "\n${verde}REMOVENDO PORTA DO SSH${fin}"
				echo ""
				fun_delpssh() {
					sed -i "/Port $pt/d" /etc/ssh/sshd_config
					service ssh restart
				}
				fun_bar 'fun_delpssh'
				echo -e "\n${verde}PORTA REMOVIDA COM SUCESSO${fin}"
				sleep 2
				fun_conexao
			} || {
				echo -e "\n${rojo}Porta invalida!"
				sleep 2
				fun_conexao
			}
		elif [[ "$resp" = '3' ]]; then
			echo -e "\n${rojo}Retornando.."
			sleep 2
			fun_conexao
		else
			echo -e "\n${rojo}Opcao invalida!"
			sleep 2
			fun_conexao
		fi
	}

	fun_sslh() {
		[[ "$(netstat -nltp | grep 'sslh' | wc -l)" = '0' ]] && {
			clear
			echo -e "\E[44;1;37m             INSTALADOR SSLH               ${fin}\n"
			echo -e "\n${amarillo}[${rojo}!${amarillo}] ${verde}A PORTA ${blanco}443 ${verde}SERA USADA POR PADRAO${fin}\n"
			echo -ne "${verde}REALMENTE DESEJA INSTALAR O SSLH ${rojo}? ${amarillo}[s/n]:${blanco} "
			read resp
			[[ "$resp" = 's' ]] && {
				verif_ptrs 443
				fun_instsslh() {
					[[ -e "/etc/stunnel/stunnel.conf" ]] && ptssl="$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)" || ptssl='3128'
					[[ -e "/etc/openvpn/server.conf" ]] && ptvpn="$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)" || ptvpn='1194'
					DEBIAN_FRONTEND=noninteractive apt-get -y install sslh
					echo -e "#Modo autónomo\n\nRUN=yes\n\nDAEMON=/usr/sbin/sslh\n\nDAEMON_OPTS='--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:$ptssl --http 127.0.0.1:80 --openvpn 127.0.0.1:$ptvpn --pidfile /var/run/sslh/sslh.pid'" >/etc/default/sslh
					/etc/init.d/sslh start && service sslh start
				}
				echo -e "\n${verde}INSTALANDO O SSLH !${fin}\n"
				fun_bar 'fun_instsslh'
				echo -e "\n${verde}INICIANDO O SSLH !${fin}\n"
				fun_bar '/etc/init.d/sslh restart && service sslh restart'
				[[ $(netstat -nplt | grep -w 'sslh' | wc -l) != '0' ]] && echo -e "\n${verde}INSTALADO COM SUCESSO !${fin}" || echo -e "\n${rojo}ERRO INESPERADO !${fin}"
				sleep 3
				fun_conexao
			} || {
				echo -e "\n${rojo}Retornando.."
				sleep 2
				fun_conexao
			}
		} || {
			clear
			echo -e "\E[41;1;37m             REMOVER O SSLH               ${fin}\n"
			echo -ne "${verde}REALMENTE DESEJA REMOVER O SSLH ${rojo}? ${amarillo}[s/n]:${blanco} "
			read respo
			[[ "$respo" = "s" ]] && {
				fun_delsslh() {
					/etc/init.d/sslh stop && service sslh stop
					apt-get remove sslh -y
					apt-get purge sslh -y
				}
				echo -e "\n${verde}REMOVENDO O SSLH !${fin}\n"
				fun_bar 'fun_delsslh'
				echo -e "\n${verde}REMOVIDO CON EXITO !${fin}\n"
				sleep 2
				fun_conexao
			} || {
				echo -e "\n${rojo}Retornando.."
				sleep 2
				fun_conexao
			}
		}
	}

	x="ok"
	fun_conexao() {
		while true $x != "ok"; do
			[[ ! -e '/home/sshplus' ]] && exit 0
			clear
			echo -e "\E[44;1;37m            SSHPLUS 🇦🇷 @diegovip7               ${fin}\n"
			echo -e "${verde}SERVICIO: ${amarillo}OPENSSH ${verde}PUERTO: ${blanco}$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="${verde}◉ "
			[[ "$(netstat -tlpn | grep 'ws-epro' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}WS-EPRO: ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'ws-epro' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts8="${verde}◉ "
			} || {
				sts8="${rojo}○ "
			}
			[[ "$(ps x | grep 'slowdns' | grep -v 'grep' | wc -l)" != '0' ]] && {
				sts9="${verde}◉ "
			} || {
				sts9="${rojo}○ "
			}
			[[ "$(netstat -tlpn | grep 'udp-custom' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}U D P: ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'udp-custom' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts7="${verde}◉ "
			} || {
				sts7="${rojo}○ "
			}

			[[ "$(netstat -tlpn | grep 'stunnel4' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}SSL+PY: ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts5="${verde}◉ "
			} || {
				sts5="${rojo}○ "
			}
			[[ "$(netstat -tlpn | grep '/usr/local/sbin/ddos' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}FIREWALL: ${verde}PUERTO: ${blanco}$(netstat -nplt | grep '/usr/local/sbin/ddos' | awk {'print $4'} | cut -d: -f2 | xargs)"
				ddos="${verde}◉ "
			} || {
				ddos="${rojo}○ "
			}

			[[ "$(netstat -tlpn | grep 'python3' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}PROXY SOCKS ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'python3' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts4="${verde}◉ "
			} || {
				sts4="${rojo}○ "
			}
			[[ -e "/usr/local/sbin/ddos" ]] && {
				echo -e "${verde}SERVICO: ${amarillo}SSL TUNNEL ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'ddos' | awk {'print $4'} | cut -d: -f2 | xargs)"
				sts3="${verde}◉ "
			} || {
				sts3="${rojo}○ "
			}
			[[ "$(netstat -tlpn | grep 'dropbear' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}DROPBEAR ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
				sts2="${verde}◉ "
			} || {
				sts2="${rojo}○ "
			}
			[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
				echo -e "${verde}SERVICIO: ${amarillo}SQUID ${verde}PUERTO: ${blanco}$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
				sts1="${verde}◉ "
			} || {
				sts1="${rojo}○ "
			}
			[[ "$(netstat -tunlp | grep 'tc' | wc -l)" != '0' ]] && {
				trojansts="${verde}◉ "
			} || {
				trojansts="${rojo}○ "
			}
			[[ "$(netstat -tunlp | grep 'v2ray' | wc -l)" != '0' ]] && {
				xv2ray="${verde}◉ "
			} || {
				xv2ray="${rojo}○ "
			}
			echo -e "\e[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${fin}"
			echo ""
			echo -e "
${cyan}-01- ${blanco}• ${amarillo}PUERTO DE TU VPS $sts6
${cyan}-02- ${blanco}• ${amarillo}SQUID PROXY $sts1
${cyan}-03- ${blanco}• ${amarillo}MENU DROPBEAR $sts2
${cyan}-04- ${blanco}• ${amarillo}AUTOINSTALACION SSL+PY $sts5
${cyan}-05- ${blanco}• ${amarillo}MENU WEBSOCKET  $sts4
${cyan}-06- ${blanco}• ${amarillo}SSL TUNNEL $sts3
${cyan}-07- ${blanco}• ${amarillo}MENU UDP $sts7
${cyan}-08- ${blanco}• ${amarillo}PYTHON3 WS-EPRO $sts8
${cyan}-09- ${blanco}• ${amarillo}MENU SLOWDNS $sts9
${cyan}-10- ${blanco}• ${amarillo}MENU V2RAY $xv2ray
${cyan}-11- ${blanco}• ${amarillo}MENU VELOCIDAD $trojansts
${cyan}-12- ${blanco}• ${amarillo}VOLVER AL MENU Inicial 
${cyan}-13- ${blanco}• ${amarillo}SLOWDNS JoaquinH2 
${cyan}-00- ${blanco}• ${amarillo}SALIR ${fin}"
			echo ""
			echo -e "\e[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${fin}"
			echo ""
			tput civis
			echo -ne "${verde} QUE DESEA HACER ${amarillo}?${rojo}?${blanco} "
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
				fun_openssh
				;;
			2 | 02)
				fun_squid
				;;
			3 | 03)
				fun_drop
				;;
			4 | 04)
				fun_openvpn
				;;
			5 | 05)
				fun_socks
				;;
			6 | 06)
				inst_ssl
				;;
			7 | 07)
				sudo rm -rf /root/holamundo.sh &&
wget https://raw.githubusercontent.com/vpsvip7/2d/main/holamundo.sh && chmod 777 holamundo.sh && ./holamundo.sh
				;;
			8 | 08)
				wget 'https://raw.githubusercontent.com/vpsvip7/2d/main/install-ws.bin' -O 'install-ws' && chmod +x install-ws && ./install-ws
				;;
			9 | 09)
				slow_setup
				;;
			10 | 10)
				v2raymanager
				exit
				;;
			11 | 11)
				source <(curl -sL https://raw.githubusercontent.com/vpsvip7/2d/refs/heads/main/menu_velocidad.sh)
				;;
			12 | 12)
				menu
				;;
			13 | 13)
				wget -q -O slow.sh https://raw.githubusercontent.com/joaquin1444/instalador/refs/heads/main/slow.sh && chmod +x slow.sh && ./slow.sh
				;;
			0 | 00)
				echo -e "${rojo}SALIENDO...${fin}"
				sleep 2
				clear
				exit
				;;
			*)
				echo -e "${rojo}OPCION INVALIDA !${fin}"
				sleep 2
				;;
			esac
		done
	}
	fun_conexao
}
