#!/bin/bash
echo -e "\033[1;36m ESTAS SON SU INFO!\033[0m"
echo ""
echo -ne "TU NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "TU KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/vpsvip7/SSHPLUS/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m SUA KEY está salva no arquivo /root/server.pub\033[0m"
echo -e "\033[1;33mGuarde-a em um local seguro, pode precisar no futuro!\033[0m"
echo ""
read -p "Pressione [Enter] para voltar ao menu ou CTRL+C para sair"
slowdns
